# Site settings
title: Matirola
email: wed@matirola.nl
description: "Matirola's wedding site"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Matirola
  location: Ketelhuis
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    name: Carola's Facebook
    url: https://www.facebook.com/carola.degroot8
  - title: facebook
    name: Mati's Facebook
    url: https://www.facebook.com/matikochen

# Postal address (add as many lines as necessary)
address:
  - line: Soesterweg 320
  - line: 3812 BH Amersfoort
  - line: '<a href="http://www.centraalketelhuis.nl" target="blank">http://www.centraalketelhuis.nl</a>'

# Credits content
credits: '"Matirola" was first mentioned by our dear friend Ohad.<br />All <a href="http://en.wikipedia.org/wiki/Royalties" title="תמלוגים" target="_blank">tamlugim</a> go to him... ;-)'

# Build settings
markdown: kramdown
permalink: pretty
